---
functional:
  - Требование 1 Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Требование 2 Пользователь должен иметь возможность фильтровать товары
  - Требование 3 Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Требование 4 Пользователь должен иметь возможность просматривать каталог товаров используясь постраничный вывод
  - Требование 5 Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Требование 6 Пользователь должен иметь возможность удалять товары из корзины и продолжить выбирать товары в каталоге 
  - Требование 7 Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
non-functional:
  - Требование 8 Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Требование 9 Сайт должен быть безопасным и защищать данные пользователя
  - Требование 10 Сайт должен иметь мобильную версию
  - Требование 11 Сайт должен быть доступен на различных устройствах
implicit:
  - Требование 12 При поиске товара пользователь ошибается в написании поискового запроса
  - Требование 13 Товар ошибочно добавлен пользователем в корзину
  - Требование 14 Поиск товара с очень длинным запросом
  - Требование 15 Выполнить поиск с использованием типов данных, отличных от текста, например, чисел или специальных символов
  - Требование 16 Выполнить поиск товара используя только заглавные буквы,проверить чувствителен ли поиск к регистру
